language: node_js
node_js:
  - "4.2.0"
  - "5.5.0"
script:
  - npm run build
  - npm run test:ci
after_success:
  # make reports and combine them
  - npm run report:ci
  # send reports to codecov
  - ./node_modules/.bin/codecov
